### PR TITLE
Add TicTacToe (aka naughts and crosses)

### PR DESCRIPTION
**Pull request by benjaminpjones**
This is a demo of how to add a game (tic-tac-toe) to the repo.

Screen Shot 2022-07-12 at 9 30 49 PM
Screen Shot 2022-07-12 at 9 27 02 PM

### CODE REVIEW

**Comment by benjaminpjones** [comment]
Doing this exercise made me realize there are some opportunities for improvement:

- Game objects and game views can be implemented in a single short file.  This means that we may not need to put each game in its own directory. This would reduce the boilerplate (new dir, index.js)
- The end of a game isn't really handled yet (#26)
- Config is hardcoded to something for baduk. We should allow variants to specify a default config (#25)
- We can move grid utils into a library in shared (map2d, make empty grid, fill grid, other 2D analogs to Array functions)
- errors aren't respected yet
   - We should expect games to throw in the constructor (illegal config) and playMove (illegal move)

**Comment by JonKo314** [comment]
I'm wondering whether we should make the code for the variants less redundant. TicTacToe is like Go without captures and a different win condition, so the two variants could share a lot of code. Maybe the only parts that should be implemented for TicTacToe is the *transition function* (where the capturing happens in Go) and the ending of the game.

**Comment by benjaminpjones** [comment]
Yeah I think a transition function would be like the functional version of playMove and exportState combined.  Still, not sure I see how we can get away from writing config validation (currently done in `TicTacToe.constructor`) or number of players/nextToPlay (although we could default to two alternating players if that's what you're getting at)

**Comment by JonKo314** [comment]
> Yeah I think a transition function would be like the functional version of playMove and exportState combined.

I don't follow, the transition function happens after players have made their move and before they are allowed to make new moves. For Baduk it has to remove captured stones, for TicTacToe it maybe just needs check if the game is over.

> Still, not sure I see how we can get away from writing config validation (currently done in `TicTacToe.constructor`) or number of players/nextToPlay

Well, config validation probably needs to be added to AbstractGame (which should maybe be renamed to AbstractVariant). Then we either write a super class for both variants or we load the same code in some different way. Coming up with good names might be the hardest part. :sweat_smile: :wink:

**Comment by benjaminpjones** [comment]
>I don't follow, the transition function happens after players have made their move and before they are allowed to make new moves. For Baduk it has to remove captured stones, for TicTacToe it maybe just needs check if the game is over.

I think if you look at playMove(), that's pretty much all that's in that method..

**Comment by JonKo314** [comment]
I think that's too much in that method then.

**Comment by benjaminpjones** [comment]
I think it might be easier to have a fruitful discussion if you make a PR or commit that changes AbstractGame to the way you think it should be. Then we have something concrete to discuss pros and cons.

I'm happy to change the way things are set up, but it's hard for me to address criticism without a clear alternative.

**Comment by JonKo314** [comment]
Sorry, you are right, I should put my thoughts into code.

**Comment by JonKo314** [comment]
Okay, I've done some refactoring of both variants to figure out how the functionalities they share could be implemented with less redundancy: https://github.com/benjaminpjones/govariants/commit/01c399f982b3ac09000481708fc0b6f4d1b3dbfc

Now we'd have to figure out if aiming for minimal redundancy is worth the trouble, or if it's simpler and sufficient to keep the variants separated.
Also I'm not sure whether this pull request is the "right" place to discuss this stuff.

**Comment by benjaminpjones** [comment]
Closed this PR, and added a section in the README that points to it: https://github.com/benjaminpjones/govariants/blob/main/README.md#creating-a-new-variant.  We can update as the process changes :)

**Pull request closed without merging**
