### PR TITLE
Game list pagination 2

### PR DESCRIPTION
**Pull request by JonKo314**
Remade game list pagination PR without meddling with NPM.

### CODE REVIEW

**Comment by JonKo314** [comment]
See https://github.com/benjaminpjones/govariants/pull/87 for earlier version of this PR.

**Comment by JonKo314** [comment]
Thanks for all the feedback @benjaminpjones!

**Review by benjaminpjones — APPROVED** [review]
Looks good! And thanks for figuring out the useFetch stuff too!

**Comment by benjaminpjones** [comment]
fyi, this change is live!

Screen Shot 2023-03-31 at 5 30 59 PM

**Pull request merged**
